import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const companies = [
  {
    name: 'Sony Corporation',
    logo: 'S',
    logoColor: '#003087',
    size: 'Lớn (>10,000 nhân viên)',
    founded: 1946,
    website: 'https://sony.com',
    linkedin: 'sony',
    description: 'Sony Corporation là tập đoàn đa quốc gia của Nhật Bản, chuyên về điện tử tiêu dùng, phim ảnh, âm nhạc và dịch vụ tài chính với hiện diện tại hơn 100 quốc gia.',
    reviewCount: 1250,
    glassdoor: 4.2,
    trustScore: 95,
  },
  {
    name: 'Rakuten, Inc.',
    logo: 'R',
    logoColor: '#BF0000',
    size: 'Lớn (>10,000 nhân viên)',
    founded: 1997,
    website: 'https://rakuten.co.jp',
    linkedin: 'rakuten',
    description: 'Rakuten là một trong những công ty thương mại điện tử và dịch vụ internet lớn nhất Nhật Bản với hơn 70 dịch vụ khác nhau trên toàn cầu.',
    reviewCount: 890,
    glassdoor: 3.9,
    trustScore: 80,
  },
  {
    name: 'DeNA Co., Ltd.',
    logo: 'D',
    logoColor: '#00A4E4',
    size: 'Trung bình (1,000-5,000)',
    founded: 1999,
    website: 'https://dena.com',
    linkedin: null,
    description: 'DeNA là công ty công nghệ Nhật Bản nổi tiếng với các sản phẩm game mobile, AI và dịch vụ internet sáng tạo.',
    reviewCount: 320,
    glassdoor: 4.0,
    trustScore: 75,
  },
  {
    name: 'Nintendo Co., Ltd.',
    logo: 'N',
    logoColor: '#E4000F',
    size: 'Lớn (>10,000 nhân viên)',
    founded: 1889,
    website: 'https://nintendo.co.jp',
    linkedin: 'nintendo',
    description: 'Nintendo là công ty game nổi tiếng thế giới với các thương hiệu Mario, Zelda, Pokémon. Trụ sở chính tại Kyoto, Nhật Bản.',
    reviewCount: 2100,
    glassdoor: 4.5,
    trustScore: 95,
  },
  {
    name: 'LINE Corporation',
    logo: 'L',
    logoColor: '#00B900',
    size: 'Lớn (>5,000 nhân viên)',
    founded: 2000,
    website: 'https://linecorp.com',
    linkedin: 'line-corporation',
    description: 'LINE là ứng dụng nhắn tin hàng đầu tại Nhật Bản, Đài Loan, Thái Lan với hàng trăm triệu người dùng hoạt động hàng tháng.',
    reviewCount: 780,
    glassdoor: 4.1,
    trustScore: 83,
  },
  {
    name: 'Tech Startup XYZ',
    logo: 'X',
    logoColor: '#6B7280',
    size: 'Nhỏ (<50 nhân viên)',
    founded: 2023,
    website: null,
    linkedin: null,
    description: null,
    reviewCount: 0,
    glassdoor: null,
    trustScore: 10,
  },
  {
    name: 'Toyota Motor Corporation',
    logo: 'T',
    logoColor: '#EB0A1E',
    size: 'Tập đoàn (>100,000 nhân viên)',
    founded: 1937,
    website: 'https://toyota.co.jp',
    linkedin: 'toyota-motor-corporation',
    description: 'Toyota là nhà sản xuất ô tô lớn nhất thế giới, đang đầu tư mạnh vào công nghệ phần mềm, xe điện và xe tự lái thế hệ mới.',
    reviewCount: 3200,
    glassdoor: 4.3,
    trustScore: 100,
  },
  {
    name: 'SoftBank Corp.',
    logo: 'SB',
    logoColor: '#FF8A00',
    size: 'Lớn (>10,000 nhân viên)',
    founded: 1981,
    website: 'https://softbank.jp',
    linkedin: null,
    description: 'SoftBank là tập đoàn viễn thông và đầu tư công nghệ hàng đầu Nhật Bản với portfolio đầu tư khổng lồ toàn cầu.',
    reviewCount: 15,
    glassdoor: 3.5,
    trustScore: 70,
  },
  {
    name: 'Mercari, Inc.',
    logo: 'M',
    logoColor: '#FF0211',
    size: 'Trung bình (1,000-5,000)',
    founded: 2013,
    website: 'https://mercari.com',
    linkedin: 'mercari',
    description: 'Mercari là nền tảng marketplace C2C lớn nhất Nhật Bản, hiện đang mở rộng sang Mỹ và các thị trường quốc tế.',
    reviewCount: 540,
    glassdoor: 4.2,
    trustScore: 80,
  },
  {
    name: 'Panasonic Holdings',
    logo: 'P',
    logoColor: '#0032A0',
    size: 'Tập đoàn (>100,000 nhân viên)',
    founded: 1918,
    website: 'https://panasonic.com',
    linkedin: 'panasonic',
    description: 'Panasonic là tập đoàn điện tử Nhật Bản với lịch sử hơn 100 năm, chuyên về điện tử gia dụng, năng lượng và hệ thống automotive.',
    reviewCount: 2800,
    glassdoor: 3.9,
    trustScore: 95,
  },
]

const jobs = [
  {
    companyIndex: 0,
    title: 'Java Developer',
    location: 'Tokyo',
    salaryMin: 400000,
    salaryMax: 600000,
    type: 'Full-time',
    postedAt: new Date('2026-04-28'),
    description: 'Chúng tôi đang tìm kiếm Java Developer tài năng để gia nhập đội ngũ phát triển phần mềm tại Sony. Bạn sẽ tham gia xây dựng và phát triển các hệ thống backend quy mô lớn phục vụ hàng triệu người dùng toàn cầu.',
    requireSkills: ['Java', 'Spring Boot', 'SQL'],
    requireJlpt: 'N3',
    requireExp: '2+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Bảo hiểm sức khỏe đầy đủ', 'Remote 2 ngày/tuần', 'Thưởng năm 4 tháng lương', 'Hỗ trợ học tiếng Nhật'],
    risks: [],
  },
  {
    companyIndex: 1,
    title: 'Frontend Developer (React)',
    location: 'Tokyo',
    salaryMin: 380000,
    salaryMax: 550000,
    type: 'Full-time',
    postedAt: new Date('2026-04-30'),
    description: 'Rakuten tìm kiếm Frontend Developer có kinh nghiệm với React và TypeScript để phát triển giao diện người dùng cho nền tảng thương mại điện tử hàng đầu Nhật Bản.',
    requireSkills: ['React', 'TypeScript', 'CSS'],
    requireJlpt: 'N2',
    requireExp: '3+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Bảo hiểm đầy đủ', 'Tiếng Anh là ngôn ngữ chính', 'Thưởng hiệu suất'],
    risks: [],
  },
  {
    companyIndex: 2,
    title: 'Python / ML Engineer',
    location: 'Osaka',
    salaryMin: 420000,
    salaryMax: 650000,
    type: 'Full-time',
    postedAt: new Date('2026-04-25'),
    description: 'Tham gia đội ngũ AI/ML của DeNA để xây dựng các mô hình học máy ứng dụng trong game và dịch vụ internet quy mô lớn.',
    requireSkills: ['Python', 'TensorFlow', 'SQL'],
    requireJlpt: 'N3',
    requireExp: '2+',
    requireEdu: 'Đại học trở lên (ưu tiên AI/Data)',
    benefits: ['Bảo hiểm sức khỏe', 'Hỗ trợ nghiên cứu AI', 'Flexible hours'],
    risks: [],
  },
  {
    companyIndex: 3,
    title: 'iOS Developer',
    location: 'Kyoto',
    salaryMin: 350000,
    salaryMax: 500000,
    type: 'Full-time',
    postedAt: new Date('2026-04-20'),
    description: 'Nintendo tìm kiếm iOS Developer để phát triển ứng dụng mobile cho hệ sinh thái game và giải trí của Nintendo.',
    requireSkills: ['Swift', 'iOS', 'Xcode'],
    requireJlpt: 'N4',
    requireExp: '2+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Bảo hiểm toàn diện', 'Game miễn phí', 'Môi trường sáng tạo', 'Thưởng tháng 13'],
    risks: [],
  },
  {
    companyIndex: 4,
    title: 'Backend Engineer (Go)',
    location: 'Tokyo',
    salaryMin: 500000,
    salaryMax: 750000,
    type: 'Full-time',
    postedAt: new Date('2026-05-01'),
    description: 'LINE tìm kiếm Backend Engineer giỏi Go để phát triển hạ tầng nhắn tin xử lý hàng tỷ tin nhắn mỗi ngày với độ trễ cực thấp.',
    requireSkills: ['Go', 'Docker', 'Kubernetes'],
    requireJlpt: 'N2',
    requireExp: '3+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Lương cạnh tranh', 'Bảo hiểm cao cấp', 'Stock options', 'Remote toàn phần'],
    risks: [],
  },
  {
    companyIndex: 5,
    title: 'PHP Developer',
    location: 'Tokyo',
    salaryMin: 250000,
    salaryMax: 350000,
    type: 'Full-time',
    postedAt: new Date('2026-05-02'),
    description: 'Công ty khởi nghiệp đang tuyển PHP Developer để phát triển web application. Môi trường năng động.',
    requireSkills: ['PHP', 'MySQL'],
    requireJlpt: 'N3',
    requireExp: '1+',
    requireEdu: 'Cao đẳng trở lên',
    benefits: ['Flexible hours'],
    risks: ['Công ty mới thành lập năm 2023, chưa có track record', 'Không rõ nguồn tài chính'],
  },
  {
    companyIndex: 6,
    title: 'DevOps Engineer',
    location: 'Nagoya',
    salaryMin: 430000,
    salaryMax: 620000,
    type: 'Full-time',
    postedAt: new Date('2026-04-15'),
    description: 'Toyota tìm kiếm DevOps Engineer để xây dựng và vận hành hạ tầng cloud cho hệ thống phần mềm xe hơi thế hệ mới.',
    requireSkills: ['AWS', 'Docker', 'Linux'],
    requireJlpt: 'N2',
    requireExp: '3+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Phúc lợi tập đoàn', 'Bảo hiểm toàn diện', 'Xe Toyota miễn phí', 'Đào tạo nghề nghiệp'],
    risks: [],
  },
  {
    companyIndex: 7,
    title: 'Data Analyst',
    location: 'Tokyo',
    salaryMin: 350000,
    salaryMax: 520000,
    type: 'Full-time',
    postedAt: new Date('2026-04-22'),
    description: 'SoftBank cần Data Analyst để phân tích dữ liệu viễn thông và hành vi người dùng nhằm tối ưu hóa chiến lược kinh doanh.',
    requireSkills: ['SQL', 'Python', 'Tableau'],
    requireJlpt: 'N3',
    requireExp: '1+',
    requireEdu: 'Đại học trở lên (ưu tiên Thống kê, Kinh tế, CNTT)',
    benefits: ['Bảo hiểm sức khỏe', 'Đào tạo chuyên sâu', 'Thưởng hiệu suất'],
    risks: [],
  },
  {
    companyIndex: 8,
    title: 'Full Stack Developer',
    location: 'Tokyo',
    salaryMin: 500000,
    salaryMax: 800000,
    type: 'Full-time',
    postedAt: new Date('2026-05-02'),
    description: 'Mercari tìm kiếm Full Stack Developer để phát triển nền tảng marketplace với scale hàng triệu giao dịch mỗi ngày.',
    requireSkills: ['React', 'Node.js', 'TypeScript'],
    requireJlpt: 'N2',
    requireExp: '3+',
    requireEdu: 'Đại học trở lên',
    benefits: ['Lương top-tier', 'Full remote', 'Stock options', 'Bảo hiểm cao cấp', 'Learning budget'],
    risks: [],
  },
  {
    companyIndex: 9,
    title: 'Embedded Systems Engineer',
    location: 'Osaka',
    salaryMin: 380000,
    salaryMax: 580000,
    type: 'Full-time',
    postedAt: new Date('2026-04-18'),
    description: 'Panasonic cần Embedded Systems Engineer để phát triển firmware cho thiết bị điện tử và hệ thống automotive thế hệ mới.',
    requireSkills: ['C++', 'Embedded Systems', 'Linux'],
    requireJlpt: 'N3',
    requireExp: '2+',
    requireEdu: 'Đại học trở lên (Kỹ thuật điện, Điện tử, CNTT)',
    benefits: ['Bảo hiểm tập đoàn', 'Hỗ trợ nhà ở', 'Đào tạo kỹ thuật chuyên sâu'],
    risks: [],
  },
]

async function main() {
  console.log('Seeding database...')

  await prisma.bookmark.deleteMany()
  await prisma.job.deleteMany()
  await prisma.company.deleteMany()
  await prisma.profile.deleteMany()
  await prisma.user.deleteMany()

  const createdCompanies = await Promise.all(
    companies.map(c => prisma.company.create({ data: c }))
  )
  console.log(`Created ${createdCompanies.length} companies`)

  const createdJobs = await Promise.all(
    jobs.map(j => {
      const { companyIndex, ...jobData } = j
      return prisma.job.create({
        data: { ...jobData, companyId: createdCompanies[companyIndex].id },
      })
    })
  )
  console.log(`Created ${createdJobs.length} jobs`)

  const hashedPassword = await bcrypt.hash('demo123456', 10)
  const demoUser = await prisma.user.create({
    data: {
      email: 'demo@jobmatch.jp',
      password: hashedPassword,
      name: 'Nguyen Van A',
      profile: {
        create: {
          skills: ['Java', 'Spring Boot', 'SQL', 'Python', 'Git', 'Linux', 'Docker'],
          japaneseLevel: 'N3',
          location: 'Tokyo',
          experienceYears: 3,
          currentTitle: 'Backend Developer',
        },
      },
    },
  })
  console.log(`Created demo user: ${demoUser.email} / demo123456`)
  console.log('Seeding complete!')
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
